Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 150

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - config.ru